spring:
  application:
    name: redneuronal
  datasource:
    username: postgres
    password: 1408
    url: jdbc:postgresql://localhost:5432/neuronaldb
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false
    mode: HTML
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8080